@startuml

title guiATP - base classes

skinparam componentStyle uml2

class Case {
  generateATP()
}

abstract class Node {
  id
}

abstract class Component

class Port

Case "1" -- "*" Component
Component "1" -- "1..*" Port
Port "1" -- "1" Node

@enduml
